In [1]:
import numpy as np
from numpy import random
E=int(input("Rows: "))
D=int(input("Columns: "))
matrix = random.rand(E,D)
print(matrix)


Rows: 3
Columns: 3
[[0.60088376 0.97370345 0.78100034]
 [0.75510585 0.2366668  0.63033435]
 [0.72370283 0.96249943 0.02636256]]
